### ISSUE TITLE
#10 장바구니 페이지 레이아웃

### ISSUE THREAD

**Issue by AI-Dev-Lex-Kim** [Kurlabo/frontend#17]
## 설명
> 장바구니 페이지 레이아웃 구현하겠습니다.

## 작업 사항
- [x] 배송지 UI 작업
- [x] 상품 금액, 할인금액, 결제 예정금액 UI 작업
- [x] 장바구니 상품 UI 작업

**Comment by parksaneon** [comment]
수고하셨습니다.
