### ISSUE TITLE
#11 header bugfix

### ISSUE THREAD

**Issue by cjy0019** [Kurlabo/frontend#20]
## 설명
> 헤더 부분에 z-index 관련 이슈와 드롭다운 관련 버그가 발견되었습니다. bug fix후 다시 업로드 하겠습니다.

## 작업 사항
- [x] 고객센터, 배송지 검색 버튼 드롭다운 이슈 처리 
- [x] 드롭다운 되었을 때 '추천순'이라는 글자가 가려지지 않는 버그 처리

**Comment by parksaneon** [comment]
수고하셨습니다.
