### ISSUE TITLE
#15 고객센터 페이지 레이아웃

### ISSUE THREAD

**Issue by nr-baek** [Kurlabo/frontend#26]
## 설명
> 고객센터 페이지 레이아웃 작업 하겠습니다.

## 작업 사항
- [x] 좌측 네비게이션바 및 템플릿 작업
- [x] 공지사항 UI 구현
- [x] 자주하는질문 UI 구현
- [x] 1:1문의 UI 구현

**Comment by parksaneon** [comment]
수고하셨습니다.
