### ISSUE TITLE
#3 메인 페이지 레이아웃

### ISSUE THREAD

**Issue by AI-Dev-Lex-Kim** [Kurlabo/frontend#3]
## 설명
> 메인페이지 레이아웃 구현하겠습니다.

## 작업 사항
- [x] 메인 케러셀 UI 작업
- [x] 이 상품 어때요 UI 작업
- [x] 알뜰 상품 UI 작업
- [x] MD의 추천 UI 작업
- [x] 오늘의 신상품 UI 작업
- [x] 지금 가장 핫한 상품 UI 작업
- [x] 인스타그램 고객후기 UI 작업

**Comment by parksaneon** [comment]
확인했습니다.
이대로 진행하시면 됩니다.
