### ISSUE TITLE
#4 상품상세페이지 레이아웃

### ISSUE THREAD

**Issue by nr-baek** [Kurlabo/frontend#4]
## 설명
> 상품 상세 페이지 레이아웃 구현하겠습니다.

## 작업 사항
- [x] 구매정보 UI 작업
- [x] 연관상품 케러셀 UI 작업
- [x] 상품설명  UI 작업
- [x] 상품이미지  UI 작업
- [x] 상세정보  UI 작업
- [x] 고객행복센터  UI 작업
- [x] 고객후기  UI 작업
- [x] 상품문의  UI 작업

**Comment by parksaneon** [comment]
확인했습니다.
이대로 진행하시면 됩니다.
