### ISSUE TITLE
#5 상품 목록 페이지 레이아웃

### ISSUE THREAD

**Issue by cjy0019** [Kurlabo/frontend#5]
## 설명
> 설명해주세요

## 작업 사항
- [x] 상품 목록 페이지 헤더
- [x] 상품 목록 페이지 레이아웃
- [x] 장바구니 모달 창 구현 
- [x]  페이지네이션 레이아웃 구현
- [x]  스크롤 버튼 구현

**Comment by parksaneon** [comment]
이대로 진행하시면 됩니다.
